Repository nom-tam-fits/nom-tam-fits, pull requests merged in 2023-07, with the labels that each got.

#458 Hierarch helper
  src/main/java/nom/tam/fits/header/extra/SBFitsExt.java
  src/main/java/nom/tam/fits/header/hierarch/Hierarch.java
  src/main/java/nom/tam/fits/header/hierarch/IHierarchKeyFormatter.java
  src/test/java/nom/tam/fits/HeaderTest.java
  src/test/java/nom/tam/util/ComplexValueTest.java
Labels: enhancement

#461 Issue 460 -- Rice compression BYTEPIX regression in 1.18.0-rc6
  src/changes/changes.xml
  src/main/java/nom/tam/fits/ImageHDU.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressor.java
  src/main/java/nom/tam/fits/compression/provider/param/hcompress/HCompressScaleParameter.java
  src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java
  src/test/java/nom/tam/fits/compression/algorithm/rice/RiceCompressTest.java
Labels: bug, enhancement

#463 Handled shared setting for quantization
  src/assembly/BUILD.md
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorOption.java
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressOption.java
Labels: enhancement

#464 Image Dimension fix
  src/main/java/nom/tam/image/compression/CompressedImageTiler.java
Labels: bug

#467 Fix ASCII table read regression
  src/main/java/nom/tam/fits/FitsFactory.java
  src/test/java/nom/tam/fits/BasicHDUTest.java
Labels: bug
