Repository nom-tam-fits/nom-tam-fits, pull requests merged in 2023-03, with the labels that each got.

#373 Try fix new CI site build error...
  pom.xml
Labels: package

#370 Issue 367: Incorrect deferred checksums from file
  src/main/java/nom/tam/fits/utilities/FitsCheckSum.java
  src/test/java/nom/tam/fits/test/ChecksumTest.java
Labels: bug

#372 Issue 371: Improved documentation of Fits constructors
  src/main/java/nom/tam/fits/Fits.java
  src/site/markdown/index.md
Labels: package

#369 Issue 368: First extension (2nd HDU) sometimes written as primary
  src/main/java/nom/tam/fits/utilities/FitsCheckSum.java
  src/main/java/nom/tam/util/FitsOutputStream.java
  src/main/java/nom/tam/util/OutputEncoder.java
  src/test/java/nom/tam/fits/test/BaseFitsTest.java
  src/test/java/nom/tam/fits/test/ChecksumTest.java
Labels: bug

#376 Coverage reporting to Coveralls.io
  .github/workflows/maven.yml
  pom.xml
Labels: package

#375 Release composition for 1.17.1
  release-HOWTO.md
  src/changes/changes.xml
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompress.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HDecompress.java
  src/main/java/nom/tam/fits/header/Checksum.java
  src/main/java/nom/tam/fits/header/DataDescription.java
  src/main/java/nom/tam/fits/header/HierarchicalGrouping.java
  src/main/java/nom/tam/fits/header/IFitsHeader.java
  src/main/java/nom/tam/fits/header/InstrumentDescription.java
  src/main/java/nom/tam/fits/header/NonStandard.java
  src/main/java/nom/tam/fits/header/ObservationDescription.java
  src/main/java/nom/tam/fits/header/ObservationDurationDescription.java
  src/main/java/nom/tam/fits/header/Standard.java
  src/main/java/nom/tam/fits/header/extra/NOAOExt.java
  src/main/java/nom/tam/fits/header/extra/SBFitsExt.java
  src/main/java/nom/tam/fits/header/extra/STScIExt.java
  src/main/java/nom/tam/fits/utilities/FitsCheckSum.java
  src/site/markdown/index.md
Labels: package

#350 Issue 349
  .github/workflows/maven.yml
  src/main/java/nom/tam/fits/compression/algorithm/gzip/GZipCompressor.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressor.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorOption.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorQuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeProcessor.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressor.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceQuantizeCompressOption.java
  src/main/java/nom/tam/fits/compression/provider/CompressorControlNameComputer.java
  src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java
  src/main/java/nom/tam/fits/compression/provider/param/api/ICompressColumnParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/api/ICompressParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/base/BundledParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/base/CompressColumnParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/base/CompressParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/base/CompressParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/hcompress/HCompressQuantizeParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/QuantizeParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZBlankColumnParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZBlankParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZBlankParameter.java_14008389361617
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZQuantizeParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZScaleColumnParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZZeroColumnParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/rice/RiceBlockSizeParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/rice/RiceBytePixParameter.java
  src/main/java/nom/tam/fits/compression/provider/param/rice/RiceCompressParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/rice/RiceQuantizeCompressParameters.java
  src/main/java/nom/tam/fits/header/extra/NOAOExt.java_3135188273660
  src/main/java/nom/tam/image/ITileOption.java
  src/main/java/nom/tam/image/compression/hdu/CompressedImageHDU.java
  src/main/java/nom/tam/image/compression/tile/TileCompressionOperation.java
  src/main/java/nom/tam/image/compression/tile/TileCompressor.java
  src/main/java/nom/tam/image/compression/tile/TileDecompressor.java
  src/main/java/nom/tam/image/compression/tile/TiledImageCompressionOperation.java
  src/test/java/nom/tam/fits/compression/ReadWriteProvidedCompressedImageTest.java
  src/test/java/nom/tam/fits/compression/TileCompressorControlNameComputerTest.java
  src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java
  src/test/java/nom/tam/fits/compression/algorithm/quant/QuantizeTest.java
  src/test/java/nom/tam/fits/compression/algorithm/rice/RiceCompressTest.java
  src/test/java/nom/tam/fits/compression/provider/CompressionProviderTest.java
  src/test/java/nom/tam/image/compression/tile/TileCompressionTest.java
Labels: bug, enhancement, API change, breaking-potential, style, standard

#352 Changes to allow alternate random access into Fits files.
  src/main/java/nom/tam/fits/Fits.java
  src/main/java/nom/tam/util/ArrayDataFile.java
  src/main/java/nom/tam/util/BufferedFileIO.java
  src/main/java/nom/tam/util/FitsFile.java
  src/main/java/nom/tam/util/RandomAccessFileIO.java
  src/test/java/nom/tam/fits/test/BaseFitsTest.java
  src/test/java/nom/tam/util/FitsFileTest.java
Labels: enhancement, API change

#356 Stream feature
  pom.xml
  src/main/checkstyle/nom-tam-fits-style.xml
  src/main/java/nom/tam/fits/FitsFactory.java
  src/main/java/nom/tam/fits/ImageData.java
  src/main/java/nom/tam/fits/StreamingTileImageData.java
  src/main/java/nom/tam/image/StandardImageTiler.java
  src/main/java/nom/tam/util/ArrayFuncs.java
  src/test/java/nom/tam/fits/StreamingTileImageDataTest.java
  src/test/java/nom/tam/fits/test/ImageTest.java
  src/test/java/nom/tam/fits/test/TilerTest.java
  src/test/java/nom/tam/util/test/ArrayFuncsTest.java
Labels: enhancement

#380 Use ZDITHER0 and seed dither random generator for each tile as prescribed
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeProcessor.java
  src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java
  src/main/java/nom/tam/fits/compression/provider/param/api/ICompressParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/base/BundledParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/base/CompressParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/QuantizeParameters.java
  src/main/java/nom/tam/fits/compression/provider/param/quant/ZDither0Parameter.java
  src/main/java/nom/tam/image/compression/tile/TileCompressor.java
  src/main/java/nom/tam/image/compression/tile/TileDecompressor.java
  src/test/java/nom/tam/fits/compression/ReadWriteProvidedCompressedImageTest.java
  src/test/java/nom/tam/fits/compression/algorithm/quant/QuantizeTest.java
Labels: enhancement, standard
