Repository nom-tam-fits/nom-tam-fits, pull requests merged in 2023-04, with the labels that each got.

#392 Issue 390: Restore back compatibility for compression as closely as possible.
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressor.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorQuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceCompressor.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceQuantizeCompressOption.java
  src/test/java/nom/tam/fits/compression/algorithm/hcompress/HCompressTest.java
  src/test/java/nom/tam/fits/compression/algorithm/rice/RiceCompressTest.java
Labels: API change

#339 Header only (null data) HDU
  src/main/java/nom/tam/fits/AsciiTable.java
  src/main/java/nom/tam/fits/AsciiTableHDU.java
  src/main/java/nom/tam/fits/BasicHDU.java
  src/main/java/nom/tam/fits/BinaryTableHDU.java
  src/main/java/nom/tam/fits/Header.java
  src/main/java/nom/tam/fits/ImageHDU.java
  src/main/java/nom/tam/fits/NullData.java
  src/main/java/nom/tam/fits/NullDataHDU.java
  src/main/java/nom/tam/fits/RandomGroupsHDU.java
  src/main/java/nom/tam/fits/UndefinedHDU.java
  src/main/java/nom/tam/fits/header/Standard.java
  src/main/java/nom/tam/fits/header/extra/NOAOExt.java_25113455894238
  src/test/java/nom/tam/fits/BasicHDUTest.java
  src/test/java/nom/tam/fits/NullDataTest.java
  src/test/java/nom/tam/fits/compression/algorithm/plio/PLIOCompressTest.java_25143011475379
  src/test/java/nom/tam/fits/test/BaseFitsTest.java
  src/test/java/nom/tam/fits/test/ImageTest.java
Labels: enhancement

#396 Consistent deferred read and Data implementations
  src/main/java/nom/tam/fits/AsciiTable.java
  src/main/java/nom/tam/fits/AsciiTableHDU.java
  src/main/java/nom/tam/fits/BasicHDU.java
  src/main/java/nom/tam/fits/BinaryTable.java
  src/main/java/nom/tam/fits/BinaryTableHDU.java
  src/main/java/nom/tam/fits/Data.java
  src/main/java/nom/tam/fits/Fits.java
  src/main/java/nom/tam/fits/FitsFactory.java
  src/main/java/nom/tam/fits/FitsUtil.java
  src/main/java/nom/tam/fits/Header.java
  src/main/java/nom/tam/fits/ImageData.java
  src/main/java/nom/tam/fits/ImageHDU.java
  src/main/java/nom/tam/fits/NullData.java
  src/main/java/nom/tam/fits/RandomGroupsData.java
  src/main/java/nom/tam/fits/RandomGroupsHDU.java
  src/main/java/nom/tam/fits/UndefinedData.java
  src/main/java/nom/tam/fits/UndefinedHDU.java
  src/test/java/nom/tam/fits/BadData.java
  src/test/java/nom/tam/fits/BasicHDUTest.java
  src/test/java/nom/tam/fits/DeferredTest.java
  src/test/java/nom/tam/fits/ImageProtectedTest.java
  src/test/java/nom/tam/fits/NullDataTest.java
  src/test/java/nom/tam/fits/ProtectedFitsTest.java
  src/test/java/nom/tam/fits/compression/ReadWriteProvidedCompressedImageTest.java
  src/test/java/nom/tam/fits/test/AsciiTableTest.java
  src/test/java/nom/tam/fits/test/BaseFitsTest.java
  src/test/java/nom/tam/fits/test/BinaryTableTest.java
  src/test/java/nom/tam/fits/test/RandomGroupsTest.java
Labels: enhancement, API change, breaking-potential, deprecate, style

#399 Fix CompressorProvider.NULL_PARAMETERS not playing nice when bundled.
  .github/workflows/maven.yml
  codecov.yml
  src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java
  src/main/java/nom/tam/fits/compression/provider/param/api/ICompressParameters.java
  src/main/java/nom/tam/image/compression/tile/TiledImageCompressionOperation.java
  src/test/java/nom/tam/image/compression/tile/TileCompressionTest.java
  src/test/java/nom/tam/image/tile/operation/TileImageCompressionOperationTest.java
Labels: bug

#400 New ability to stream cutouts from compressed images
  src/main/java/nom/tam/fits/StreamingTileImageData.java
  src/main/java/nom/tam/fits/compression/algorithm/hcompress/HCompressorQuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/quant/QuantizeOption.java
  src/main/java/nom/tam/fits/compression/algorithm/rice/RiceQuantizeCompressOption.java
  src/main/java/nom/tam/fits/compression/provider/CompressorProvider.java
  src/main/java/nom/tam/image/compression/CompressedImageTiler.java
  src/main/java/nom/tam/image/compression/hdu/CompressedImageHDU.java
  src/main/java/nom/tam/util/ArrayFuncs.java
  src/site/markdown/index.md
  src/test/java/nom/tam/image/compression/CompressedImageTilerTest.java
  src/test/java/nom/tam/util/DefaultMethodsTest.java
Labels: enhancement

#402 Use JDK 17 for CI
  .github/workflows/gh-package.yml
  .github/workflows/maven.yml
  .github/workflows/site.yml
Labels: package
